blank_issues_enabled: false
contact_links:
  - name: Global Discussions
    url: https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/discussions
    about: Please ask and answer questions here.
  - name: Whitelist Discussions
    url: https://github.com/Ultimate-Hosts-Blacklist/whitelist/discussions
    about: Please ask and answer questions related to the whitelist here.
  - name: Main Repository
    url: https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist
    about: Find more information about the main repository here.
  - name: Blacklist
    url: https://github.com/Ultimate-Hosts-Blacklist/blacklist/issues
    about: Please report blacklist review requests here.
